<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-01-22 04:28:24',
                'updated_at' => '2019-01-22 04:28:24',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2019-01-22 04:28:24',
                'updated_at' => '2019-02-01 08:55:07',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2019-01-22 04:28:24',
                'updated_at' => '2019-02-01 08:55:07',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2019-01-22 04:28:24',
                'updated_at' => '2019-02-01 08:55:07',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2019-01-22 04:28:24',
                'updated_at' => '2019-02-01 08:55:02',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2019-01-22 04:28:24',
                'updated_at' => '2019-01-22 10:16:00',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2019-01-22 04:28:24',
                'updated_at' => '2019-01-22 10:16:00',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2019-01-22 04:28:24',
                'updated_at' => '2019-01-22 10:16:00',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2019-01-22 04:28:24',
                'updated_at' => '2019-01-22 10:16:00',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2019-01-22 04:28:24',
                'updated_at' => '2019-02-01 08:55:02',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2019-01-22 04:30:05',
                'updated_at' => '2019-02-01 08:55:07',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Posts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2019-01-22 04:30:07',
                'updated_at' => '2019-02-01 08:55:07',
                'route' => 'voyager.posts.index',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Pages',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2019-01-22 04:30:09',
                'updated_at' => '2019-02-01 08:55:07',
                'route' => 'voyager.pages.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2019-01-22 04:30:12',
                'updated_at' => '2019-01-22 10:16:00',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Sensors',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-terminal',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-01-22 10:08:57',
                'updated_at' => '2019-01-23 02:36:55',
                'route' => 'voyager.sensors.index',
                'parameters' => 'null',
            ),
            15 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'Locations',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-01-23 02:15:56',
                'updated_at' => '2019-01-23 02:38:11',
                'route' => 'voyager.locations.index',
                'parameters' => 'null',
            ),
            16 => 
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => 'Datapoints',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-calendar',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2019-01-23 02:43:50',
                'updated_at' => '2019-01-23 02:53:08',
                'route' => 'voyager.datapoints.index',
                'parameters' => 'null',
            ),
            17 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'User Token',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-wifi',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2019-02-01 08:52:26',
                'updated_at' => '2019-02-06 02:31:21',
                'route' => 'voyager.usertokens.index',
                'parameters' => 'null',
            ),
            18 => 
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Tests',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2019-02-05 02:30:48',
                'updated_at' => '2019-02-05 02:30:48',
                'route' => 'voyager.tests.index',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}